### ISSUE TITLE
custom styles

### ISSUE THREAD

**Issue by sevamoo** [cheeaun/3d-earth#1]
Thanks a lot for your neat work. 
I was wondering if it is possible to use my own customized Mapbox styles in this framework? 
I couldn't manage that unfortunately. you can find it here: https://sevamoo.github.io/3d/

Thanks for any suggestion.

**Comment by cheeaun** [comment]
Technically you could change the `style` https://github.com/cheeaun/3d-earth/blob/19fe0abc482432dea774b8f498fb5dd2d62095ae/index.html#L207

**Comment by sevamoo** [comment]
Thanks a lot. My issue was that my custom maps were empty at that zoom level. 
However, I was wondering if there is a way to have a dynamic mapbox GL layer. Seemingly this is not working as if I increase the zoom to higher values (initially set to 1), the 3d map doesn't look proper anymore.
Thanks a lot for the great work.
Best
Vahid

**Comment by cheeaun** [comment]
My initial attempt for this is to have a dynamic mapbox GL layer but little do I know how hard it gets 😅

So, in a "best-effort" way, I decided to make a raster copy of the vector tiles and use it as a layer for the globe. Technically to make this 3D earth, MapBox GL is not needed as you could just use any static image of earth. The only accidental "advantage" for this demo is that the earth tiles are dynamically generated from Mapbox vector tiles 😬

Also, increasing the zoom level will potentially increase the dimension of the raster copy but my experiments lead to browsers crashing, or rather my low-spec Macbook 12" hanging a few times 😅

**Comment by sevamoo** [comment]
All was great for me! 
Thanks for sharing your work here.
Best
Vahid
